project:
  type: website

website:
  title: "Climate Change Impacts Bushfires: Rising Risks in Southeast Australia"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Anaiff

format:
  html:
    theme: cosmo
    css: styles.css



